# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'cobaui.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.setEnabled(True)
        MainWindow.resize(678, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 0, 641, 51))
        self.label1.setStyleSheet("KLASIFIKASI JENIS TUMBUHAN MANGGA BERDASARKAN BENTUK DAUN DENGAN MENGGUNAKAN METODE GLCM DAN K-NEAREST NEIGHBORS")
        self.label1.setObjectName("label1")
        self.buttonopen = QtWidgets.QPushButton(self.centralwidget)
        self.buttonopen.setGeometry(QtCore.QRect(20, 60, 75, 23))
        self.buttonopen.setObjectName("buttonopen")
        self.buttongray = QtWidgets.QPushButton(self.centralwidget)
        self.buttongray.setGeometry(QtCore.QRect(20, 280, 75, 23))
        self.buttongray.setObjectName("buttongray")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 90, 211, 181))
        self.label.setText("")
        self.label.setPixmap(QtGui.QPixmap("manggo2.jpg"))
        self.label.setScaledContents(True)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(20, 310, 211, 181))
        self.label_2.setText("")
        self.label_2.setPixmap(QtGui.QPixmap("gray.jpg"))
        self.label_2.setScaledContents(True)
        self.label_2.setWordWrap(False)
        self.label_2.setObjectName("label_2")
        self.buttonglcm = QtWidgets.QPushButton(self.centralwidget)
        self.buttonglcm.setGeometry(QtCore.QRect(260, 60, 75, 23))
        self.buttonglcm.setObjectName("buttonglcm")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(260, 90, 401, 121))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.buttonclasifi = QtWidgets.QPushButton(self.centralwidget)
        self.buttonclasifi.setGeometry(QtCore.QRect(260, 230, 75, 23))
        self.buttonclasifi.setObjectName("buttonclasifi")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 678, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label1.setToolTip(_translate("MainWindow", "<html><head/><body><p align=\"center\">KLASIFIKASI JENIS TUMBUHAN MANGGA BERDASARKAN BENTUK DAUN DENGAN MENGGUNAKAN METODE GLCM DAN K-NEAREST NEIGHBORS</p></body></html>"))
        self.label1.setWhatsThis(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-weight:600;\">KLASIFIKASI JENIS TUMBUHAN MANGGA BERDASARKAN BENTUK DAUN DENGAN MENGGUNAKAN METODE GLCM DAN K-NEAREST NEIGHBORS</span></p></body></html>"))
        self.label1.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:10pt; font-weight:600; color:#000000;\">KLASIFIKASI JENIS TUMBUHAN MANGGA BERDASARKAN BENTUK DAUN DENGAN MENGGUNAKAN METODE GLCM DAN K-NEAREST NEIGHBORS</span></p></body></html>"))
        self.buttonopen.setText(_translate("MainWindow", "Browse"))
        self.buttongray.setText(_translate("MainWindow", "Grayscale"))
        self.buttonglcm.setText(_translate("MainWindow", "GLCM"))
        self.buttonclasifi.setText(_translate("MainWindow", "Classification"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
